#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: "{build}"

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that run after cloning repository
#install:
#  - cinst NuGet.CommandLine 

# to run your custom scripts instead of automatic MSBuild
build_script:
  - "%APPVEYOR_BUILD_FOLDER%\build\build.bat" "0.9.%APPVEYOR_BUILD_VERSION%"

 #artifacts:
 # - path: '*.nupkg'
  
# to disable automatic tests
test: off

# to disable deployment
deploy: off
