#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: "0.9.{build}"

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012 R2

# scripts that run after cloning repository
branches:
  # whitelist
  only:
    - master

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: "build\\build.bat"

artifacts:
  - path: '**\*.nupkg' # find all NuGet packages recursively
  
# to disable automatic tests
test: off